version: '3.1'

services:
  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data_container:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456

volumes:
  mongodb_data_container:
#<----- if server will not connect then try disable firewall if not already ----->
